name: Deploy Nuxt App to VPS

on:
  push:
    branches:
      - main # デプロイ対象ブランチ

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: tempest
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # 作業ディレクトリへ
            cd /home/tempest/Documents/expo-2025-waiting-map

            # 最新コードを取得
            git fetch --all
            git reset --hard origin/main

            # Node 22 を使う（nvm）
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 22

            # 依存パッケージ更新＆ビルド
            pnpm install
            pnpm build

            # PM2 再起動
            pm2 restart expo-waiting-map
